# Generated by Django 5.2.4 on 2025-08-08 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_jobalert'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas personales sobre esta vacante')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='applicants.applicantprofile')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.jobpost')),
            ],
            options={
                'verbose_name': 'Vacante Guardada',
                'verbose_name_plural': 'Vacantes Guardadas',
                'ordering': ['-saved_at'],
                'unique_together': {('job_post', 'applicant')},
            },
        ),
    ]
