# Generated by Django 5.2.4 on 2025-08-12 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='companies.company'),
        ),
    ]
