# Generated by Django 5.2.4 on 2025-08-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpost_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones'},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vacante', 'verbose_name_plural': 'Vacantes'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas del reclutador'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Postulado'), ('reviewing', 'En revisión'), ('shortlisted', 'Preseleccionado'), ('interviewed', 'Entrevistado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(help_text='Descripción detallada de la vacante'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(help_text='Requisitos y cualificaciones'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills_required',
            field=models.ManyToManyField(blank=True, through='jobs.JobPostSkill', to='jobs.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='jobpostskill',
            unique_together={('job_post', 'skill')},
        ),
    ]
