name: meraki-django-app
services:
- name: web
  source_dir: /
  github:
    repo: tu-usuario/tu-repositorio
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm sistema.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    value: ${SECRET_KEY}
    type: SECRET
  - key: ALLOWED_HOSTS
    value: ".ondigitalocean.app"
  - key: DATABASE_URL
    value: "sqlite:///db.sqlite3"

static_sites:
- name: static
  source_dir: /staticfiles
  routes:
  - path: /static
  - path: /media
