# Generated by Django 5.2.4 on 2025-08-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='skills',
            field=models.ManyToManyField(through='applicants.ApplicantSkill', to='jobs.skill'),
        ),
    ]
