# Generated by Django 5.2.4 on 2025-08-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Un nombre descriptivo para identificar esta alerta', max_length=100, verbose_name='Nombre de la Alerta')),
                ('keywords', models.CharField(help_text='Palabras clave separadas por comas', max_length=200, verbose_name='Palabras Clave')),
                ('location', models.CharField(blank=True, help_text='Ciudad, estado o país', max_length=100, verbose_name='Ubicación')),
                ('employment_type', models.CharField(blank=True, choices=[('', 'Cualquier tipo'), ('full_time', 'Tiempo Completo'), ('part_time', 'Medio Tiempo'), ('contract', 'Contrato'), ('freelance', 'Freelance'), ('internship', 'Práctica'), ('remote', 'Remoto')], max_length=20, verbose_name='Tipo de Empleo')),
                ('experience_level', models.CharField(blank=True, choices=[('', 'Cualquier nivel'), ('entry', 'Nivel de Entrada'), ('junior', 'Junior'), ('mid', 'Intermedio'), ('senior', 'Senior'), ('lead', 'Líder'), ('executive', 'Ejecutivo')], max_length=20, verbose_name='Nivel de Experiencia')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Mínimo')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Máximo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Alerta Activa')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por Email')),
                ('frequency', models.CharField(choices=[('immediate', 'Inmediato'), ('daily', 'Diario'), ('weekly', 'Semanal')], default='daily', max_length=20, verbose_name='Frecuencia de Notificaciones')),
                ('jobs_found', models.PositiveIntegerField(default=0, verbose_name='Empleos Encontrados')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Última Verificación')),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True, verbose_name='Última Notificación Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='applicants.applicantprofile', verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'Alerta de Empleo',
                'verbose_name_plural': 'Alertas de Empleo',
                'ordering': ['-created_at'],
            },
        ),
    ]
