# Generated by Django 5.2.4 on 2025-08-08 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_received_email', models.BooleanField(default=True)),
                ('application_received_in_app', models.BooleanField(default=True)),
                ('application_status_update_email', models.BooleanField(default=True)),
                ('application_status_update_in_app', models.BooleanField(default=True)),
                ('job_approved_email', models.BooleanField(default=True)),
                ('job_approved_in_app', models.BooleanField(default=True)),
                ('new_job_match_email', models.BooleanField(default=False)),
                ('new_job_match_in_app', models.BooleanField(default=True)),
                ('profile_viewed_email', models.BooleanField(default=False)),
                ('profile_viewed_in_app', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('in_app_notifications_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Inicio de horas silenciosas (no enviar notificaciones)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fin de horas silenciosas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_received', 'Postulación Recibida'), ('application_status_update', 'Actualización de Estado'), ('job_approved', 'Vacante Aprobada'), ('job_rejected', 'Vacante Rechazada'), ('new_job_match', 'Nueva Vacante que Coincide'), ('profile_viewed', 'Perfil Visto'), ('message_received', 'Mensaje Recibido'), ('system_update', 'Actualización del Sistema')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('method', models.CharField(choices=[('email', 'Email'), ('in_app', 'En la Aplicación'), ('sms', 'SMS'), ('push', 'Push Notification')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('failed', 'Fallido'), ('read', 'Leído')], default='pending', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, help_text='URL a la que redirigir al hacer clic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx')],
            },
        ),
    ]
